name: Build and Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Скачиваем код
      - name: Checkout code
        uses: actions/checkout@v2

      # Запуск тестов
      - name: Run tests
        run: sudo apt-get install libhdf5-openmpi-dev && mkdir build && cd build && cmake .. && make && mpirun -np 4 ./tests
